apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tiltak-refusjon-loginproxy
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://tiltak-refusjon-loginproxy.dev-adeo.no
    - https://tiltak-refusjon-loginproxy.dev.adeo.no
  azure:
    application:
      enabled: true
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: AAD_REDIRECT_URL
      value: https://tiltak-refusjon-loginproxy.dev-adeo.no/oauth2/callback
    - name: AAD_LOGOUT_REDIRECT_URL
      value: https://tiltak-refusjon-loginproxy.dev-adeo.no/oauth2/callback
    - name: SESSION_KEY
      value: tullenokkel
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
