apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tiltak-refusjon-innside
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://tiltak-refusjon-innside.dev-adeo.no
    - https://tiltak-refusjon-innside.dev.adeo.no
  azure:
    application:
      enabled: true
  liveness:
    path: /isAlive
    initialDelay: 30
  readiness:
    path: /isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 1
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: AAD_REDIRECT_URL
      value: https://tiltak-refusjon-innside.dev-adeo.no/oauth2/callback
    - name: AAD_LOGOUT_REDIRECT_URL
      value: https://tiltak-refusjon-innside.dev-adeo.no/oauth2/callback
    - name: SESSION_KEY
      value: tullenokkel
    - name: DECORATOR_SCRIPT
      value: https://app-q0.adeo.no/internarbeidsflatedecorator/v2/static/js/head.v2.min.js
    - name: DECORATOR_STYLING
      value: https://app-q0.adeo.no/internarbeidsflatedecorator/v2/static/css/main.css
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
