ingress: https://tiltak-refusjon.adeo.no
env:
  AAD_REDIRECT_URL: https://tiltak-refusjon.adeo.no/oauth2/callback
  AAD_LOGOUT_REDIRECT_URL: https://tiltak-refusjon.adeo.no/oauth2/callback
  API_CLIENT_ID: c3251b3e-1ee1-4f60-b409-0475cdf014d6
  DECORATOR_HOST: https://internarbeidsflatedecorator.nais.adeo.no
host:
  - internarbeidsflatedecorator.nais.adeo.no
slack_alert_channel: arbeidsgiver-notifications
tenant: nav.no