name: Trigges utenfra

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  bygg:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Sjekk ut frontend
        uses: actions/checkout@v2
        with:
          repository: navikt/tiltak-refusjon
          path: tiltak-refusjon
          ref: master
      - name: Installer avhengigheter
        run:  yarn --cwd tiltak-refusjon install --production --ignore-scripts --no-optional
      - name: Bygg
        run: yarn --cwd tiltak-refusjon build